---
- hosts: web_servers
  become: true
  tasks:
    - name: copy default html to web servers
      copy:
        src: files/default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: '0644'
