---
- name: Update package cache on Ubuntu
  apt:
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Update package cache on CentOS
  dnf:
    update_cache: yes
  when: ansible_distribution == "CentOS"
